#!/usr/bin/env python3

import argparse
import scalavista


DEFAULT_PORT = 9317

PEDANTIC_SCALACOPTIONS = ('-deprecation '
                          '-feature '
                          '-unchecked '
                          '-Ywarn-dead-code '
                          '-Ywarn-value-discard '
                          '-Ywarn-unused:imports '
                          '-Ywarn-unused:patvars '
                          '-Ywarn-unused:privates '
                          '-Ywarn-unused:locals '
                          '-Ywarn-unused:params '
                          '-Xlint:_')


parser = argparse.ArgumentParser()
parser.add_argument('-d', '--debug', help='switch on debug mode',
                    action='store_true')
parser.add_argument('-t', '--trace', help='switch on trace mode',
                    action='store_true')
parser.add_argument('-r', '--recursive', help='look for Scala source files in all subdirectories - applies only in the absence of a scalavista.json file',
                    action='store_true')
parser.add_argument('--scalacopts', nargs='*', help='Scala compiler options')
parser.add_argument('--pedantic', action='store_true', help='set pedantic scalac options; overrides --scalacopts')
parser.add_argument('-p', '--port', type=int, help='The scalavista server port', default=DEFAULT_PORT)

args = parser.parse_args()

if args.pedantic:
    scalac_opts = PEDANTIC_SCALACOPTIONS
elif args.scalacopts:
    scalac_opts = ' '.join(args.scalacopts)
else:
    scalac_opts = ''

scalavista.launch(args.port, scalac_opts, args.debug, args.trace, args.recursive)
